[package]
name = "fizzbuzz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
cranelift = "0"
cranelift-jit = "0"
cranelift-module = "0"
peg = "0"
test_bin = "0"
